import Head from 'next/head'
import BallContainer from '../components/BallContainer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BallContainer />
      </main>

    </div>
  )
}
